// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/hello.proto

package protoSamples

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SampleServiceClient is the client API for SampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleServiceClient interface {
	GetSampleID(ctx context.Context, in *SampleRequestAll, opts ...grpc.CallOption) (*SampleResponseAll, error)
	GetSampleByID(ctx context.Context, in *SampleRequestByID, opts ...grpc.CallOption) (*SampleResponseByID, error)
}

type sampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleServiceClient(cc grpc.ClientConnInterface) SampleServiceClient {
	return &sampleServiceClient{cc}
}

func (c *sampleServiceClient) GetSampleID(ctx context.Context, in *SampleRequestAll, opts ...grpc.CallOption) (*SampleResponseAll, error) {
	out := new(SampleResponseAll)
	err := c.cc.Invoke(ctx, "/protoSamples.SampleService/GetSampleID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sampleServiceClient) GetSampleByID(ctx context.Context, in *SampleRequestByID, opts ...grpc.CallOption) (*SampleResponseByID, error) {
	out := new(SampleResponseByID)
	err := c.cc.Invoke(ctx, "/protoSamples.SampleService/GetSampleByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleServiceServer is the server API for SampleService service.
// All implementations should embed UnimplementedSampleServiceServer
// for forward compatibility
type SampleServiceServer interface {
	GetSampleID(context.Context, *SampleRequestAll) (*SampleResponseAll, error)
	GetSampleByID(context.Context, *SampleRequestByID) (*SampleResponseByID, error)
}

// UnimplementedSampleServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSampleServiceServer struct {
}

func (UnimplementedSampleServiceServer) GetSampleID(context.Context, *SampleRequestAll) (*SampleResponseAll, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSampleID not implemented")
}
func (UnimplementedSampleServiceServer) GetSampleByID(context.Context, *SampleRequestByID) (*SampleResponseByID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSampleByID not implemented")
}

// UnsafeSampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SampleServiceServer will
// result in compilation errors.
type UnsafeSampleServiceServer interface {
	mustEmbedUnimplementedSampleServiceServer()
}

func RegisterSampleServiceServer(s grpc.ServiceRegistrar, srv SampleServiceServer) {
	s.RegisterService(&SampleService_ServiceDesc, srv)
}

func _SampleService_GetSampleID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleRequestAll)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).GetSampleID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoSamples.SampleService/GetSampleID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).GetSampleID(ctx, req.(*SampleRequestAll))
	}
	return interceptor(ctx, in, info, handler)
}

func _SampleService_GetSampleByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SampleRequestByID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SampleServiceServer).GetSampleByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protoSamples.SampleService/GetSampleByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SampleServiceServer).GetSampleByID(ctx, req.(*SampleRequestByID))
	}
	return interceptor(ctx, in, info, handler)
}

// SampleService_ServiceDesc is the grpc.ServiceDesc for SampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protoSamples.SampleService",
	HandlerType: (*SampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSampleID",
			Handler:    _SampleService_GetSampleID_Handler,
		},
		{
			MethodName: "GetSampleByID",
			Handler:    _SampleService_GetSampleByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hello.proto",
}
